tasks:
    path: /
    controller: App\Controller\TaskController::index

myTasks:
    path: /myTasks
    controller: App\Controller\TaskController::myTasks

tasks_detail:
    path: /detail/{id}
    controller: App\Controller\TaskController::detail

tasks_creation:
    path: /creation
    controller: App\Controller\TaskController::creation

task_edit:
    path: /edit/{id}
    controller: App\Controller\TaskController::edit

task_delete:
    path: /delete/{id}
    controller: App\Controller\TaskController::delete
  
register:
    path: /register
    controller: App\Controller\UserController::register

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout
